import re, math

with open('pcb/halo-90.kicad_pcb', 'r') as f:
    pcb = f.read()

# Pass 1: find all net definitions
net_matches = re.findall(r'^\s*\(net\s+(\d+)\s+"([^"]+)"\)', pcb, flags=re.MULTILINE)
nets = {int(m[0]): m[1] for m in net_matches}
name_to_netid = {m[1]: int(m[0]) for m in net_matches}

# We need to give names to segments generated by halo.js based on their connection topology! 
# A much simpler approach: run halo.js AGAIN with my new rewritten `(net ID)` additions to physically rebuild all the charlieplexed led arrays from scratch using javascript.
